### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by TheNathanSpace** [Samuel-Martineau/Potions-HUD-Fabric#3]
Hi! I really like this mod and have used it for a while. But in order to use it with another mod that displays coordinates, I have to patch jar with changes to the y-offset using Krakatau, jd-gui, etc.

I think adding a proper config (file and hopefully in-game) would improve the mod and make it a lot more flexible for users.

I'd be willing to do this and submit a PR, but wanted to check with you before doing so.

Since Fabric doesn't have official config file capabilities, I'm planning to use [Cloth Config](https://shedaniel.gitbook.io/cloth-config/). I plan for it to be an optional external dependency.

Anyway, let me know if you have any thoughts! Thanks.

**Comment by Samuel-Martineau** [comment]
I really don’t have time to add any new features because of school right now, but If you submit a PR, I’ll be happy to review and merge it.

**Comment by Samuel-Martineau** [comment]
Could you test the new Jar (1.2.0) and confirm me it works?

**Comment by TheNathanSpace** [comment]
Looks like 1.2.0 works great on 1.18.1 (restarted with changed config in-between each image):

![2021-12-11_10 16 24](https://user-images.githubusercontent.com/46632454/145685635-8236467a-d7a0-4b1d-8b9f-fb40b669a3a0.png)
![2021-12-11_10 17 33](https://user-images.githubusercontent.com/46632454/145685638-ce529a57-fa5c-4f4b-bf8c-24b54c42fa4e.png)
![2021-12-11_10 18 43](https://user-images.githubusercontent.com/46632454/145685642-1ac133d3-b887-401b-8c06-096eb35213e0.png)

**Comment by Samuel-Martineau** [comment]
Perfect! Thanks for your contribution
