### ISSUE TITLE
Changing hud position doesn't work properly 

### ISSUE THREAD

**Issue by Bazyliii** [Samuel-Martineau/Potions-HUD-Fabric#5]
![2022-03-15_12 39 53](https://user-images.githubusercontent.com/67436562/158370443-8ecc5122-30e9-4789-8b53-891bea033779.png)
Game version is 1.18.2
And this is clean install 

Additionally it makes a lot of log spam like this
![image](https://user-images.githubusercontent.com/67436562/158370742-1ef19c93-d7aa-4e01-9450-2ecbcd282af3.png)

**Comment by Samuel-Martineau** [comment]
I don’t have time to look into this right now, but as soon as I do, I will tell you. In the mean time, could you use the default position?

**Comment by Bazyliii** [comment]
Yeah ofc. take your time man :)

**Comment by Samuel-Martineau** [comment]
I think this is fixed by 6f9f9e5b19f6dac2e8973680c7c810f315329ef4. Could you confirm if it is working as expected?

**Comment by Bazyliii** [comment]
Yeah it is working great! Thx
