### ISSUE TITLE
Potion HUD not scaling with the game resolution

### ISSUE THREAD

**Issue by Scarlaid** [Samuel-Martineau/Potions-HUD-Fabric#6]
![image](https://user-images.githubusercontent.com/90851437/171685887-300ce12d-e7fe-4891-a8c0-308a3cba88e9.png)

**Comment by Scarlaid** [comment]
oh wait, my bad, it was another mod

**Comment by Scarlaid** [comment]
ignore the above
this was the issue i wanna mention
![image](https://user-images.githubusercontent.com/90851437/171686601-84a75cb9-4cfd-4a7d-9a32-7bcb1520024e.png)

**Comment by Samuel-Martineau** [comment]
What do you mean “not scaling”? Do you mean the font size?

**Comment by Scarlaid** [comment]
> What do you mean “not scaling”? Do you mean the font size?

The HUD, because of it only scale at the left-side, changing the x-offset to the right leading to the above image
The font being too big is also a problem but I guess it depends so different story
